name: React build
on:
  push: # client Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - client

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build # React Build
        run: |
          cd client
          npm install
          npm run build
