name: React build
on:
  push: # client Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - client

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies # 의존 파일 설치
        run: npm install

      - name: Build # React Build
        run: npm run build
